### ISSUE TITLE
Animation roll

### ISSUE THREAD

**Issue by Yungsaas** [lgkonline/so2money#2]
I noticed that the only skin that has has a name underneath it is the one you win. 

That takes away from the experience since you can always tell ecactly what you get before it lands on a skin.

**Comment by lgkonline** [comment]
On desktop you can always see the names of each skin. Because of missing place on mobile I decided to show only the name of the target skin. 
To improve the experience I could only show the name after the animation has finished. 🤔

**Comment by lgkonline** [comment]
Next thing to do: Improve animation and make it work with the new "provably fair algorithm" (https://fair.so2.money).

**Comment by lgkonline** [comment]
Instead of building the animation, use some Open Source stuff!

Some sources I could use as references/use the code:
* http://demo.st-marron.info/roulette/sample/demo.html

**Comment by lgkonline** [comment]
Built a better animation with After Effects + Lottie.js.
