### ISSUE TITLE
Inspiration sources

### ISSUE THREAD

**Issue by lgkonline** [lgkonline/so2money#3]
This thread is for collecting links to possible inspiration sources for this project. 
If you find interesting pages, feel free to create a comment and link to them. 😎

**Comment by lgkonline** [comment]
Loot Systems
* https://www.hypedrop.com/en/boxes/view/budget-master
* https://www.g2a.com/
* https://datdrop.com
* https://www.csgolive.com/case/Millionaire%20Case%20%28vIRL%29
* https://skin.club/de/cases/open/glock

**Comment by lgkonline** [comment]
Provably Fair System
* https://dicesites.com/provably-fair
* https://repl.it/@datdrop/datdrop-provably-fair

**Comment by lgkonline** [comment]
CSS Ideas
Interesting CSS library by Adobe:
* [Interesting CSS library by Adobe](https://github.com/adobe/spectrum-css)
* https://css-tricks.com/css-animation-libraries/
* Animated icons https://useanimations.com
  * Showcase https://thesvbd.github.io/Lottie-examples/#top
* Animating a logo https://www.cassie.codes/posts/creating-my-logo-animation/

React / JavaScript
* React without Webpack and Babel https://formidable.com/blog/2019/no-build-step/

**Comment by Felixtensee** [comment]
https://www.csgolive.com/case/Millionaire%20Case%20%28vIRL%29

**Comment by Felixtensee** [comment]
https://skin.club/de/cases/open/glock

**Comment by lgkonline** [comment]
CSS Animation libraries
https://css-tricks.com/css-animation-libraries/

**Comment by lgkonline** [comment]
E-Commerce solutions
* https://snipcart.com/

**Comment by lgkonline** [comment]
* https://www.youtube.com/watch?v=IHF2AdXoEF8
* https://www.youtube.com/watch?v=pTnNUSNghuI&list=PLtkPGCygOklE0oFgEiMR3xZGhgdatPdwc

**Comment by lgkonline** [comment]
Background pattern from https://swordshield.pokemon.com/de-de/pokemon-galar-region/weezing/ (?)

**Comment by lgkonline** [comment]
Nice framework for future projects: https://stenciljs.com
Using Web Components now, is used by companies like Apple.

**Comment by Felixtensee** [comment]
https://gyazo.com/c37e70cdf54c2e0843e4c2b7f04bea44

For depositing your skins a little Tutorial before starting or even for the deposit.
